
[campfire_overhaul]
	#How long of a burn time should campfire have by default (in ticks, ticks = 1/20 of second):
	#Range: > 0
	campfireDefaultLifeTime = 2000
	#Should campfire burn indefinitely? Overrides default life time
	campfireInfiniteLifeTime = false
	#Default state of campfire: true - unlit, false - lit:
	campfireCreatedUnlit = true
	#Value, by which the fuel time of thrown item is multiplied
	#e.g. you throw a stick into a campfire. With multiplier 1 it will give a campfire 100 ticks = 5 seconds of time. With multiplier 4 it will give it 20 seconds of time. 
	#Range: > 1
	campfireFuelMultiplier = 1
	#Enable/disable double flint ignition mechanic.
	doubleFlintIgnition = true
	#Chance of successfully igniting a campfire using two flints. By default, it's 33% (0.33).
	#Range: 0.0 ~ 1.0
	flintIgniteChance = 0.33

